name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-iso:
    name: Build ISO
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Free disk space
        run: |
          sudo rm -rf \
            /usr/share/dotnet /usr/local/lib/android /{usr,var}/lib/snapd \
            /opt/{az,containerd,hostedtoolcache,ghc,google,mssql-tools,pipx*} \
            $HOME/.{rustup,cargo,dotnet}
          sudo docker image prune --all --force || true
          sudo docker builder prune -a --force || true
          df -h

      - name: Build ISO
        run: bash ./scripts/ci.sh

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v6
        with:
          name: x13s-iso
          path: |
            result/iso/*.iso
            SHA256SUMS
          if-no-files-found: error
